version: '3'
services:
  odoo-update:
    build:
      context: .
      dockerfile: Dockerfile
    image: trustcode/docker-odoo:11.0
    network_mode: host
    command: autoupdate
    volumes:
      - ~/.ssh:/home/temp/.ssh
    environment:
      PG_USER: postgres_user
      PG_PASSWORD: 123
      ODOO_VERSION: 11.0
      ODOO_ENTERPRISE: 1
      TRUSTCODE_ENTERPRISE: 1
      DATABASE: database
      DISABLE_LOGFILE: 1
